# Site settings
title: "Piña Data Lab"
email: jeramirezp.pdl@gmail.com
url: "https://pinaxdbioinfo.github.io"
description: "Consultoría en Análisis de Datos e Inteligencia de Negocio"
keywords: "Dashboard, bioinformatica, Análisis de datos, estadistica"
skills: "¿Necesitas convertir tus datos en mejores decisiones? Si buscas dar un mejor seguimiento a tu negocio, entender a tus clientes, automatizar reportes, visualizar indicadores o analizar datos complejos, puedo ayudarte. Desde desarrollo de dashboards, automatización de procesos, análisis estadístico hasta soluciones de bioinformática para emprendimientos, pymes, instituciones y proyectos de investigación."
meta_author: José Emilio Ramírez Piña

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0e752a #0e752a
  primary-rgb: "14,117,42" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 170f70 #170f70

# Footer settings
footer:
  copyright: Piña Data Lab
  location: Locación
  social: Información adicional y otros medios de contacto
  credits: Creditos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Instagram
    url: https://www.instagram.com/pinadatalab/
  - title: linkedin
    url: http://www.linkedin.com/in/jose-emilio-ramirez-71855a201
  - title: github
    url: https://github.com/PinaXDbioinfo
  - title: envelope
    url: mailto:jeramirezp.pdl@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Querétaro, Querétaro

# Credits content
credits: 'Esta página web fue diseñada basanda en una plantilla llamada Freelancer la cual es de libre uso. Link: <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
